### ISSUE TITLE
Tutorial text: trials == horizon?

### ISSUE THREAD

**Issue by haz** [ataitler/IPPC2023#11]
Not sure this part makes a lot of sense to me:

>  The number of trials is called the horizon, and in this example the horizon is set to 40, which indicates that the domain will be simulated for 40 time steps.

Wouldn't the simulator execute several trials (not specified in the domain/problem it seems?) at a max depth of 40 (i.e., the horizon) is this case?

**Comment by ataitler** [comment]
No you are right, it does not make sense. trial is an episode, the horizon is the number of steps in an episode. You understand correctly.
It will be corrected.

**Comment by haz** [comment]
There a way to specify the # of trials in the RDDL?

**Comment by haz** [comment]
Closed by #13

**Comment by ataitler** [comment]
Closed
